#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.86.98:3306/store?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      max-active: 30
      min-idle: 5
      max-wait: 10000
      validation-query: select 'x'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
#server:
#  port: 8443
#  ssl:
#    key-store: store.jks
#    key-password: 1528634975109
#    key-store-type: JKS


